spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles: local
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 운영 환경
---
spring:
  profiles: prod
